language: cpp
dist: trusty
compiler: clang
os:
- linux

before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get -qq update
- sudo apt-get install -y cmake libcurl4-openssl-dev rapidjson-dev

install:
- cmake . && make

branches:
  only:
  - master

notifications:
  email: false

env:
  global:
  - LANG="en_US.UTF-8"
