shallow_clone: true
clone_folder: c:\projects\libssllabs

environment:
  matrix:
  - ARCH: "i686"
  - ARCH: "x86_64"

branches:
  only:
    - master

skip_commits:
  # Add [ci skip] to commit messages for docfixes, etc to reduce load on queue
  message: /\[ci skip\]/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

#needed to download other deps
  - cinst curl

before_build:
  - ps: cd "c:\projects\libssllabs"
  - cmd: cmake .

build:
  project: ssllabs.sln

