shallow_clone: true
clone_folder: c:\projects\libssllabs

environment:
  matrix:
  - ARCH: "i686"
  - ARCH: "x86_64"

branches:
  only:
    - master

skip_commits:
  message: /\[ci skip\]/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  #let's use the pre-installed mingw
  - ps: $env:PATH = 'C:\MinGW\bin;C:\MinGW\mingw32\bin;C:\MinGW\msys\1.0\bin;' + $env:PATH
  #we copy mingw32-make to have a "make" executable
  - cmd: copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe

build_script:
  - ps: cd "c:\projects\libssllabs"
  - cmd: cmake -G "MinGW Makefiles" .
  - cmd: sh -c "make V=1"